USE [master]
GO

CREATE DATABASE [AdvertisementNF] ON  PRIMARY 
( NAME = N'AdvertisementNF_Data', FILENAME = N'D:\SQLDatabase\AdvertisementNF_Data.MDF' , SIZE = 418624KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'AdvertisementNF_Log', FILENAME = N'D:\SQLDatabase\AdvertisementNF_Log.LDF' , SIZE = 3400960KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'AdvertisementNF', @new_cmptlevel=80
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AdvertisementNF].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [AdvertisementNF] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AdvertisementNF] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AdvertisementNF] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AdvertisementNF] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AdvertisementNF] SET ARITHABORT OFF 
GO
ALTER DATABASE [AdvertisementNF] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AdvertisementNF] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [AdvertisementNF] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AdvertisementNF] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AdvertisementNF] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AdvertisementNF] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AdvertisementNF] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AdvertisementNF] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AdvertisementNF] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AdvertisementNF] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AdvertisementNF] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AdvertisementNF] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AdvertisementNF] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AdvertisementNF] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AdvertisementNF] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AdvertisementNF] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AdvertisementNF] SET  READ_WRITE 
GO
ALTER DATABASE [AdvertisementNF] SET RECOVERY FULL 
GO
ALTER DATABASE [AdvertisementNF] SET  MULTI_USER 
GO
ALTER DATABASE [AdvertisementNF] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO
ALTER DATABASE [AdvertisementNF] SET DB_CHAINING OFF 

USE [AdvertisementNF]
CREATE ROLE RTUsers AUTHORIZATION db_securityadmin; 
