GRANT SELECT, UPDATE, INSERT ON Users TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON Roles TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON Banks TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON Localities TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON Units TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON TypeOfActivitys TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON Clients TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON Contractors TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON Orders TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON Products TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON ProductTypes TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON TypeOfActivityInProducts TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON ParameterInProductTypes TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON ProductCosts TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON CategoryOfProducts TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON Setting TO RTUsers;
GRANT SELECT, UPDATE, INSERT ON IAccessMatrix TO RTUsers;

GRANT SELECT, UPDATE, INSERT, DELETE ON Referencebook TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON ReferencebookParameter TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON ReferencebookApplicability TO RTUsers;

GRANT SELECT, UPDATE, INSERT, DELETE ON Payments TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON Accounts TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON Acts TO RTUsers;

GRANT SELECT, UPDATE, INSERT, DELETE ON ProductionAreas TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON TypeOfActivityInProdAreas TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON Operations TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON TypeOfActivityInOperations TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON ParameterInOperations TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON TechCards TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON WorkInTechCards TO RTUsers;
GRANT SELECT, UPDATE, INSERT, DELETE ON OperationInWorks TO RTUsers;

